objects/ErrorMessage__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Error_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error Message</label>
    <nameField>
        <displayFormat>Error Message-{0000}</displayFormat>
        <label>Error Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>Error Message</description>
        <label>ErrorMessage</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TrackingHistory__c</fullName>
        <description>Tracking History from Checkpoint Manager</description>
        <label>TrackingHistory</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created By User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>History of Logs - mostly used for error logs</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SystemSettings__c.object
<CustomObject>
    <fields>
        <fullName>CheckptMgrEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This setting determines if checkpoint manager is enabled or disabled</description>
        <label>CheckptMgrEnabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CheckptMgrRemainingCPUThresholdPct__c</fullName>
        <defaultValue>5</defaultValue>
        <description>This setting will determine if checkpoint manager will throw exception or not upon the limit threshold.</description>
        <label>CheckptMgrRemainingCPUThresholdPct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CheckptMgrRemainingQueryRowsThresholdPct__c</fullName>
        <defaultValue>10</defaultValue>
        <description>This setting determines number of query rows left in current transaction and throws exception if it is below threshold. 

To disable, make the threshold 0.</description>
        <label>CheckptMgrRemainingQueryRowsThresholdPct</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CheckptMgrRemainingSOQLThresholdPct__c</fullName>
        <defaultValue>5</defaultValue>
        <description>This setting will check how many SOQL left in current transaction and raise an exception if it is below the threshold.

Note: to disable this setting, change the remaining threshold to 0.</description>
        <label>CheckptMgrRemainingSOQLThresholdPct</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LoggingMgrEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This setting determines if logging manager is enabled or disabled</description>
        <label>LoggingMgrEnabled</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is created to store value for all system level options. For now storing : CheckpointManager, PlatformCacheManager, etc..</description>
    <label>System Settings</label>
</CustomObject>

classes/LoggingManagerTest.cls
/**
 * Created by user on 6/22/2017.
 */

@IsTest
private class LoggingManagerTest {

    @testSetup
    static void setup() {
        SystemSettings__c setting = new SystemSettings__c();
        setting.name = 'default';
        setting.LoggingMgrEnabled__c = true;
        setting.CheckptMgrEnabled__c = true;
        setting.CheckptMgrRemainingSOQLThresholdPct__c = 6;
        setting.CheckptMgrRemainingQueryRowsThresholdPct__c = 6;
        setting.CheckptMgrRemainingCPUThresholdPct__c = 6;
        upsert setting;
    }


    @isTest
    static void testBehaviorLogMessage() {
        SystemSettings__c setting = SystemSettings__c.getInstance('default');
        Test.startTest();
        Log logObject=new Log();
        ICheckpointManager checkpointManager=ServiceFactory.getInstance().getCheckpointManagerInstance();
        LoggingManager loggingManager = new LoggingManager();
        checkpointManager.checkpoint('Log cpm 1');
        logObject.errorMessage='Some error message';
        loggingManager.logMessage(logObject);
        
        checkpointManager.checkpoint('Log cpm 2');
        
        try{
            Integer exceptionNumber = 1/0;
        }catch(Exception e){
            ILoggingManager iloggingManager = ServiceFactory.getInstance().getLoggingManagerInstance();
            iloggingManager.logMessage(Log.ProcessType.Warning,e);
            iloggingManager.logMessage(Log.ProcessType.Warning,e,'Apex',e.getStackTraceString());
            iloggingManager.logMessage(Log.ProcessType.Warning,e,e.getMessage());
            iloggingManager.logMessage(Log.ProcessType.Warning,e,e.getMessage(),'Apex',e.getStackTraceString());
            iloggingManager.logMessage(Log.ProcessType.Warning,e,e.getMessage(),JSON.serialize('Test'));
            iloggingManager.logMessage(Log.ProcessType.Warning,e,e.getMessage(),JSON.serialize('Test'),'Apex',e.getStackTraceString());
            iloggingManager.logMessage(Log.ProcessType.Warning,e,e.getMessage(), new CustomClass());
            iloggingManager.logMessage(Log.ProcessType.Warning,e,e.getMessage(), new CustomClass(),'Apex',e.getStackTraceString());
            iloggingManager.logMessage(Log.ProcessType.Warning,e,e.getMessage(),new List<String>{'Test'});
            iloggingManager.logMessage(Log.ProcessType.Warning,e,e.getMessage(),new List<String>{'Test'},'Apex',e.getStackTraceString());
        }
        
        Test.stopTest();
        
        List<Log__c> logs=[select ErrorMessage__c,TrackingHistory__c,User__c from Log__c];
        System.assertEquals(12, logs.size());
    }

    @isTest
    public static void testInvocableLogMessage(){
        Test.startTest();

        List<LoggingManager.LogRequest> loggingManagerLogRequest = new List<LoggingManager.LogRequest>();
        LoggingManager.LogRequest logRequest = new LoggingManager.LogRequest();
        logRequest.payload = 'Test';
        logRequest.errorMessage = 'Test';
        logRequest.processType = 'ActiveDisclosureFacade';
        loggingManagerLogRequest.add(logRequest);
        LoggingManager.invocableLogMessage(loggingManagerLogRequest);

        Test.stopTest();
        List<Log__c> logs=[select ErrorMessage__c,TrackingHistory__c,User__c from Log__c];
        System.assertEquals(1,logs.size());
    }
        
    public class CustomClass{}
}